apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started-app
spec:
  selector:
    matchLabels:
      app: yarn
  replicas: 2
  template:
    metadata:
      labels:
        app: yarn
    spec:
      containers:
      - name: getting-started-app
        image: hatimmirghani/getting-started:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: getting-started-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: yarn
